name: Pipeline
permissions:
  contents: read
on: [push]
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
        - uses: action/checkout@v2
        - name: Setup Python environment 
          uses: actions/setup-python@v1.1.1
        - name: Install requirements
          run: pip install -q -r requirements.txt
        - name: Lint Code
          run:
            flake8 --ignore=E05,E231 *.py
            pylint --disable=C0301 --disable=C0326 *.py
        - name: Run unit tests
          run:
            python -m pytest -v  

